# Generated by Django 4.2.1 on 2023-05-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_cargo', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=70)),
                ('pais', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigojira', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=70)),
                ('horas', models.FloatField(max_length=10)),
                ('fecha', models.CharField(max_length=11)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.rol')),
            ],
        ),
    ]
